name: Mise à jour Supabase programmée

on:
  workflow_dispatch:   # Permet le lancement manuel
  schedule:
    - cron: '0 0 * * 1'  # toutes les lundi 00h00

jobs:
  update-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase pandas

      - name: Run update script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python bdd_foot.py
